{-# LANGUAGE OverloadedStrings #-}

-- |
-- Build orchestration for the Python backend.
--
-- Reads @corefn.json@ for every compiled module, emits one Python module
-- file per PureScript module, the runtime (@_purepy_runtime.py@), the
-- built-in FFI shims, and (when a Main module exists) a @main.py@ entry
-- point so the program runs with @python3 OUTPUT_DIR\/main.py@.
--
-- Unlike the Julia sibling there is no loader: Python's own import
-- statements resolve the dependency order, provided the output directory
-- is on @sys.path@ (main.py arranges this for the entry-point case).
--
module Language.PureScript.Python.Make
  ( compile
  , CompileOptions(..)
  ) where

import Prelude

import Control.Monad (forM, forM_, unless, when)
import Data.Aeson (decodeFileStrict)
import Data.Aeson.Types (parseMaybe)
import Data.List (find)
import qualified Data.Map.Strict as Map
import Data.Maybe (catMaybes)
import qualified Data.Set as Set
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import System.Directory (createDirectoryIfMissing, doesDirectoryExist, doesFileExist, copyFile)
import System.FilePath ((</>), takeFileName)
import System.FilePath.Glob (glob)

import qualified Language.PureScript as P
import qualified Language.PureScript.CoreFn as CoreFn
import qualified Language.PureScript.CoreFn.FromJSON as CoreFn

import Language.PureScript.Python.CodeGen (generateModulePy)
import Language.PureScript.Python.CodeGen.Common (pyModuleName, pyFileName, pyForeignModuleName, pyForeignFileName, identToPyName)
import Language.PureScript.Python.Foreigns (builtinForeigns)

data CompileOptions = CompileOptions
  { inputDir :: FilePath    -- ^ Directory containing corefn.json files (usually "output")
  , outputDir :: FilePath   -- ^ Directory for Python output (usually "output-py")
  }

-- | Compile all modules in the input directory
compile :: CompileOptions -> IO ()
compile opts = do
  let coreFnGlob = inputDir opts </> "*" </> "corefn.json"
  corefnFiles <- glob coreFnGlob

  when (null corefnFiles) $
    putStrLn "No corefn.json files found. Run 'spago build' (with a backend configured) first."

  unless (null corefnFiles) $ do
    putStrLn $ "Found " ++ show (length corefnFiles) ++ " modules to compile"
    createDirectoryIfMissing True (outputDir opts)

    -- Parse all modules up front (we need the import graph for the
    -- foreign-shim warnings)
    mods <- fmap catMaybes . forM corefnFiles $ \corefnFile -> do
      mJson <- decodeFileStrict corefnFile
      case mJson >>= parseMaybe CoreFn.moduleFromJSON of
        Nothing -> do
          putStrLn $ "Error: failed to parse " ++ corefnFile
          return Nothing
        Just (_version, cfModule) -> return (Just cfModule)

    -- Emit each module
    forM_ mods $ \cfModule -> do
      let mn = CoreFn.moduleName cfModule
          outFile = outputDir opts </> pyFileName mn
      TIO.writeFile outFile (moduleFile cfModule)
      putStrLn $ "Compiled: " ++ T.unpack (pyModuleName mn)

    -- Runtime + built-in FFI shims; user shims (ffi-py/) copied last so they win
    generateRuntime (outputDir opts)
    forM_ builtinForeigns $ \(name, content) ->
      TIO.writeFile (outputDir opts </> name) content
    copyUserForeigns (outputDir opts)

    -- Warn about reachable modules with foreign imports but no shim on disk
    let mainMod = find (\m -> CoreFn.moduleName m == P.ModuleName "Main") mods
        ordered = loadOrder mods mainMod
        byName = Map.fromList [(CoreFn.moduleName m, m) | m <- mods]
    forM_ ordered $ \mn ->
      forM_ (Map.lookup mn byName) $ \m ->
        unless (null (CoreFn.moduleForeign m)) $ do
          let shim = outputDir opts </> pyForeignFileName mn
          exists <- doesFileExist shim
          unless exists $
            putStrLn $ "Warning: " ++ T.unpack (pyModuleName mn)
                     ++ " has foreign imports but no " ++ takeFileName shim
                     ++ " - provide one in ffi-py/"

    -- Entry point. Named __main__.py (run with `python3 OUTPUT_DIR`):
    -- a file named main.py would OVERWRITE the module file of a
    -- PureScript module called Main on case-insensitive filesystems
    -- (macOS APFS), and dunder names can never collide with PureScript
    -- module names.
    case mainMod of
      Just _ -> do
        TIO.writeFile (outputDir opts </> "__main__.py") $ T.unlines
          [ "# Generated by purepy - program entry point"
          , "import os"
          , "import sys"
          , "sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))"
          , "import Main"
          , "Main.main()"
          ]
        putStrLn $ "Run with: python3 " ++ outputDir opts
      Nothing ->
        putStrLn "No Main module found - no main.py entry point generated"

    putStrLn "Done!"

-- | Full text of one generated module file
moduleFile :: CoreFn.Module CoreFn.Ann -> T.Text
moduleFile cfModule =
  let mn@(P.ModuleName name) = CoreFn.moduleName cfModule
      isPrimModule (P.ModuleName n) = T.isPrefixOf "Prim" n
      imports = dedupe
        [ depMn
        | depMn <- map snd (CoreFn.moduleImports cfModule)
        , depMn /= mn
        , not (isPrimModule depMn)
        ]
      foreigns = CoreFn.moduleForeign cfModule
  in T.unlines $
       [ "# Generated by purepy from PureScript module: " <> name
       , "# Do not edit this file directly"
       , "from _purepy_runtime import _runtime_lazy, _js_number_string, _tco_run, _pattern_fail, _len, _mk"
       ]
       ++ [ "import " <> pyModuleName depMn | depMn <- imports ]
       ++ (if null foreigns
             then []
             else [ "from " <> pyForeignModuleName mn <> " import ("
                    <> T.intercalate ", " (map identToPyName foreigns) <> ")" ])
       ++ [ "" , generateModulePy cfModule ]

dedupe :: Ord a => [a] -> [a]
dedupe = go Set.empty
  where
    go _ [] = []
    go seen (x:xs)
      | x `Set.member` seen = go seen xs
      | otherwise = x : go (Set.insert x seen) xs

-- | Topologically-ordered module list (dependencies first). When a Main
-- module exists, restrict to its transitive closure; otherwise load
-- everything. (Used only for the foreign-shim warnings - Python needs
-- no loader.)
loadOrder :: [CoreFn.Module CoreFn.Ann] -> Maybe (CoreFn.Module CoreFn.Ann) -> [P.ModuleName]
loadOrder mods mainMod =
  let compiled = Set.fromList (map CoreFn.moduleName mods)
      depsOf = Map.fromList
        [ ( CoreFn.moduleName m
          , dedupe [ d | d <- map snd (CoreFn.moduleImports m)
                       , d /= CoreFn.moduleName m
                       , d `Set.member` compiled ] )
        | m <- mods ]
      roots = case mainMod of
        Just m -> [CoreFn.moduleName m]
        Nothing -> map CoreFn.moduleName mods
      -- DFS post-order: dependencies emitted before dependents
      visit (visited, acc) mn
        | mn `Set.member` visited = (visited, acc)
        | otherwise =
            let (visited', acc') =
                  foldl visit (Set.insert mn visited, acc)
                        (Map.findWithDefault [] mn depsOf)
            in (visited', acc' ++ [mn])
  in snd (foldl visit (Set.empty, []) roots)

-- | Copy user-supplied FFI shims from ./ffi-py into the output directory
copyUserForeigns :: FilePath -> IO ()
copyUserForeigns outDir = do
  let ffiDir = "ffi-py"
  exists <- doesDirectoryExist ffiDir
  when exists $ do
    files <- glob (ffiDir </> "*.py")
    forM_ files $ \f -> do
      copyFile f (outDir </> takeFileName f)
      putStrLn $ "FFI (user): " ++ takeFileName f

-- | Runtime support module
generateRuntime :: FilePath -> IO ()
generateRuntime dir = TIO.writeFile (dir </> "_purepy_runtime.py") $ T.unlines
  [ "# PureScript Python Runtime"
  , "# Generated by purepy"
  , "import math as _math"
  , "import sys as _sys"
  , ""
  , "# Generated code multiplies Python frames per PS call; the corpus's"
  , "# non-trampolined recursion needs headroom over CPython's default 1000."
  , "_sys.setrecursionlimit(10000)"
  , ""
  , "# len, captured: generated pattern-match code must not depend on the"
  , "# builtin name being unshadowed in the importing module."
  , "_len = len"
  , ""
  , "def _pattern_fail(module_name):"
  , "    raise RuntimeError(\"Pattern match failed in module \" + module_name)"
  , ""
  , "# Close a lifted lambda (module-level def) back over its free"
  , "# variables, restoring a unary closure. See the lambda-lifting note"
  , "# in the code generator: CPython caps paren nesting, so lambdas are"
  , "# hoisted to flat defs and re-curried here."
  , "def _mk(f, *env):"
  , "    return lambda x: f(*env, x)"
  , ""
  , "# The TCO dispatch loop: loop returns (1, args) to continue or"
  , "# (0, result) to stop. Function-call-per-iteration so closures created"
  , "# in the loop body capture per-iteration bindings."
  , "def _tco_run(loop, args):"
  , "    r = (1, args)"
  , "    while r[0] == 1:"
  , "        r = loop(*r[1])"
  , "    return r[1]"
  , ""
  , "# Lazy initialization wrapper for mutually recursive top-level bindings."
  , "# state: 0 = uninitialized, 1 = initializing, 2 = done"
  , "def _runtime_lazy(name, module_name, init):"
  , "    state = [0, None]"
  , "    def thunk():"
  , "        if state[0] == 2:"
  , "            return state[1]"
  , "        if state[0] == 1:"
  , "            raise RuntimeError(name + \" was needed before it finished initializing (module \" + module_name + \")\")"
  , "        state[0] = 1"
  , "        state[1] = init()"
  , "        state[0] = 2"
  , "        return state[1]"
  , "    return thunk"
  , ""
  , "# JS Number.prototype.toString formatting, built on Python's shortest-"
  , "# roundtrip repr (same digits, different placement rules). Decimal"
  , "# notation for 1e-6 <= |n| < 1e21, exponential with explicit sign"
  , "# otherwise, integer-valued doubles without a point. Used by the"
  , "# Data.Show and Data.Number.Format shims."
  , "def _js_number_string(n):"
  , "    if _math.isnan(n):"
  , "        return \"NaN\""
  , "    if n == _math.inf:"
  , "        return \"Infinity\""
  , "    if n == -_math.inf:"
  , "        return \"-Infinity\""
  , "    if n == 0.0:"
  , "        return \"0\""
  , "    s = repr(n)"
  , "    neg = s.startswith(\"-\")"
  , "    if neg:"
  , "        s = s[1:]"
  , "    parts = s.split(\"e\")"
  , "    mant = parts[0]"
  , "    ex = int(parts[1]) if len(parts) == 2 else 0"
  , "    dot = mant.find(\".\")"
  , "    intlen = len(mant) if dot == -1 else dot"
  , "    digits = mant.replace(\".\", \"\")"
  , "    pp = intlen + ex      # decimal point position: n = 0.digits * 10^pp"
  , "    k0 = len(digits)"
  , "    digits = digits.lstrip(\"0\")"
  , "    pp -= k0 - len(digits)"
  , "    digits = digits.rstrip(\"0\")"
  , "    k = len(digits)"
  , "    if k <= pp <= 21:"
  , "        body = digits + \"0\" * (pp - k)"
  , "    elif 0 < pp <= 21:"
  , "        body = digits[:pp] + \".\" + digits[pp:]"
  , "    elif -6 < pp <= 0:"
  , "        body = \"0.\" + \"0\" * (-pp) + digits"
  , "    else:"
  , "        e = pp - 1"
  , "        body = (digits[0] + (\".\" + digits[1:] if k > 1 else \"\")"
  , "                + \"e\" + (\"+\" if e >= 0 else \"-\") + str(abs(e)))"
  , "    return \"-\" + body if neg else body"
  ]
