-- | Data.Array surface, including the ST-backed functions (nub, group)
-- | and stable-sort behaviour.
module Test.Arrays where

import Prelude

import Data.Array as A
import Data.Array.NonEmpty as NEA
import Data.Foldable (foldl, foldr, foldMap, sum, product, maximum, minimum, intercalate)
import Data.Int (odd)
import Data.Maybe (Maybe(..))
import Data.Traversable (traverse, sequence, scanl, scanr)
import Data.Tuple (Tuple(..), snd)
import Data.Unfoldable (unfoldr)
import Effect (Effect)
import Effect.Console (log)

t :: String -> String -> Effect Unit
t name v = log ("TEST " <> name <> ": " <> v)

main :: Effect Unit
main = do
  log "=== Test.Arrays ==="
  t "range-up" (show (A.range 1 5))
  t "range-down" (show (A.range 5 1))
  t "range-single" (show (A.range 3 3))
  t "replicate" (show (A.replicate 3 'q'))
  t "replicate-zero" (show (A.replicate 0 'q'))
  t "replicate-negative" (show (A.replicate (-2) 'q'))
  t "length" (show (A.length [ 1, 2, 3 ]))
  t "length-empty" (show (A.length ([] :: Array Int)))
  t "index-ok" (show (A.index [ 10, 20, 30 ] 1))
  t "index-oob" (show (A.index [ 10, 20, 30 ] 3))
  t "index-negative" (show (A.index [ 10, 20, 30 ] (-1)))
  t "head" (show (A.head [ 1, 2 ]))
  t "head-empty" (show (A.head ([] :: Array Int)))
  t "last" (show (A.last [ 1, 2 ]))
  t "tail" (show (A.tail [ 1, 2, 3 ]))
  t "init" (show (A.init [ 1, 2, 3 ]))
  t "uncons" (show (A.uncons [ 1, 2, 3 ]))
  t "unsnoc" (show (A.unsnoc [ 1, 2, 3 ]))
  t "cons" (show (A.cons 0 [ 1, 2 ]))
  t "snoc" (show (A.snoc [ 1, 2 ] 3))
  t "insertAt" (show (A.insertAt 1 99 [ 1, 2 ]))
  t "insertAt-end" (show (A.insertAt 2 99 [ 1, 2 ]))
  t "insertAt-oob" (show (A.insertAt 5 99 [ 1, 2 ]))
  t "deleteAt" (show (A.deleteAt 0 [ 1, 2 ]))
  t "deleteAt-oob" (show (A.deleteAt 2 [ 1, 2 ]))
  t "updateAt" (show (A.updateAt 1 9 [ 1, 2 ]))
  t "modifyAt" (show (A.modifyAt 1 (_ * 10) [ 1, 2 ]))
  t "reverse" (show (A.reverse [ 1, 2, 3 ]))
  t "concat" (show (A.concat [ [ 1 ], [], [ 2, 3 ] ]))
  t "concatMap" (show (A.concatMap (\x -> [ x, x ]) [ 1, 2 ]))
  t "filter" (show (A.filter odd [ 1, 2, 3, 4, 5 ]))
  t "partition" (show (A.partition odd [ 1, 2, 3, 4, 5 ]))
  t "mapMaybe" (show (A.mapMaybe (\x -> if x > 2 then Just (x * 10) else Nothing) [ 1, 2, 3, 4 ]))
  t "catMaybes" (show (A.catMaybes [ Just 1, Nothing, Just 3 ]))
  t "mapWithIndex" (show (A.mapWithIndex (\i x -> i * x) [ 5, 5, 5 ]))
  t "sort" (show (A.sort [ 3, 1, 2 ]))
  t "sort-empty" (show (A.sort ([] :: Array Int)))
  t "sortBy-desc" (show (A.sortBy (flip compare) [ 1, 3, 2 ]))
  -- stability: equal keys keep their original relative order
  t "sort-stable"
    ( show
        ( map snd
            ( A.sortBy (\(Tuple a _) (Tuple b _) -> compare a b)
                [ Tuple 1 "a", Tuple 0 "b", Tuple 1 "c", Tuple 0 "d", Tuple 1 "e" ]
            )
        )
    )
  t "slice" (show (A.slice 1 3 [ 0, 1, 2, 3, 4 ]))
  t "slice-negative" (show (A.slice (-2) 5 [ 0, 1, 2, 3, 4 ]))
  t "slice-empty" (show (A.slice 3 1 [ 0, 1, 2, 3, 4 ]))
  t "take" (show (A.take 2 [ 1, 2, 3 ]))
  t "take-more" (show (A.take 9 [ 1, 2, 3 ]))
  t "drop" (show (A.drop 2 [ 1, 2, 3 ]))
  t "drop-more" (show (A.drop 9 [ 1, 2, 3 ]))
  t "takeWhile" (show (A.takeWhile (_ < 3) [ 1, 2, 3, 1 ]))
  t "dropWhile" (show (A.dropWhile (_ < 3) [ 1, 2, 3, 1 ]))
  t "span" (show (A.span (_ < 3) [ 1, 2, 3, 1 ]))
  t "zip" (show (A.zip [ 1, 2, 3 ] [ "a", "b" ]))
  t "zipWith" (show (A.zipWith (*) [ 1, 2, 3 ] [ 10, 20, 30 ]))
  t "unzip" (show (A.unzip [ Tuple 1 "a", Tuple 2 "b" ]))
  t "findIndex" (show (A.findIndex (_ == 2) [ 1, 2, 3, 2 ]))
  t "findLastIndex" (show (A.findLastIndex (_ == 2) [ 1, 2, 3, 2 ]))
  t "elemIndex" (show (A.elemIndex 3 [ 1, 2, 3 ]))
  t "elem" (show (A.elem 3 [ 1, 2, 3 ]))
  t "notElem" (show (A.notElem 9 [ 1, 2, 3 ]))
  t "nub" (show (A.nub [ 3, 1, 3, 2, 1 ]))
  t "nubEq" (show (A.nubEq [ 3, 1, 3, 2, 1 ]))
  t "union" (show (A.union [ 1, 2 ] [ 2, 3 ]))
  t "intersect" (show (A.intersect [ 1, 2, 3 ] [ 2, 3, 4 ]))
  t "difference" (show (A.difference [ 1, 2, 3 ] [ 2 ]))
  t "group" (show (map NEA.toArray (A.group [ 1, 1, 2, 3, 3, 3 ])))
  t "groupBy" (show (map NEA.toArray (A.groupBy (\a b -> odd a == odd b) [ 1, 3, 2, 4, 5 ])))
  t "foldl" (show (foldl (-) 100 [ 1, 2, 3 ]))
  t "foldr" (show (foldr (-) 0 [ 10, 20, 30 ]))
  t "foldMap" (foldMap show [ 1, 2, 3 ])
  t "sum" (show (sum [ 1, 2, 3 ]))
  t "sum-number" (show (sum [ 1.5, 2.5 ]))
  t "product" (show (product [ 1, 2, 3, 4 ]))
  t "maximum" (show (maximum [ 1, 3, 2 ]))
  t "minimum" (show (minimum ([] :: Array Int)))
  t "intercalate" (intercalate ", " [ "a", "b", "c" ])
  t "traverse-just" (show (traverse Just [ 1, 2, 3 ]))
  t "traverse-nothing" (show (traverse (\x -> if x > 1 then Nothing else Just x) [ 1, 2 ]))
  t "traverse-big" (show (map A.length (traverse Just (A.range 1 1000))))
  t "sequence" (show (sequence [ Just 1, Just 2 ]))
  t "scanl" (show (scanl (+) 0 [ 1, 2, 3 ]))
  t "scanr" (show (scanr (+) 0 [ 1, 2, 3 ]))
  t "unfoldr" (show (unfoldr (\n -> if n > 4 then Nothing else Just (Tuple n (n + 1))) 1 :: Array Int))
  t "all" (show (A.all (_ > 0) [ 1, 2 ]))
  t "any" (show (A.any (_ > 1) [ 1, 2 ]))
  t "bind-array" (show ([ 1, 2 ] >>= \x -> [ x, x * 10 ]))
  t "apply-array" (show ([ (_ + 1), (_ * 2) ] <*> [ 10, 20 ]))
  t "append" (show ([ 1, 2 ] <> [ 3 ]))
