-- | Int and Number semantics: arithmetic, division families, bit ops,
-- | radix conversion, Number formatting (the JS toString rules), and
-- | Math functions including DomainError->NaN edges.
module Test.Numbers where

import Prelude

import Data.Int as Int
import Data.Int.Bits as Bits
import Data.Number as Num
import Data.Ord (abs, signum)
import Effect (Effect)
import Effect.Console (log)

t :: String -> String -> Effect Unit
t name v = log ("TEST " <> name <> ": " <> v)

main :: Effect Unit
main = do
  log "=== Test.Numbers ==="
  -- Int arithmetic
  t "int-add" (show (2 + 3))
  t "int-negate" (show (negate 5))
  t "int-abs" (show (abs (-7)))
  t "int-signum" (show (signum (-7)))
  -- Euclidean div/mod (PS semantics: mod always >= 0)
  t "int-div-pos" (show (7 / 2))
  t "int-div-neg" (show ((-7) / 2))
  t "int-mod-pos" (show (7 `mod` 2))
  t "int-mod-neg" (show ((-7) `mod` 2))
  t "int-mod-negdiv" (show (7 `mod` (-2)))
  t "int-div-zero" (show (7 / 0))
  t "int-mod-zero" (show (7 `mod` 0))
  t "int-gcd" (show (gcd 12 18))
  t "int-lcm" (show (lcm 4 6))
  -- truncating quot/rem
  t "int-quot-pos" (show (Int.quot 7 2))
  t "int-quot-neg" (show (Int.quot (-7) 2))
  t "int-rem-pos" (show (Int.rem 7 2))
  t "int-rem-neg" (show (Int.rem (-7) 2))
  t "int-pow" (show (Int.pow 2 10))
  t "int-pow-zero" (show (Int.pow 5 0))
  t "int-pow-wrap" (show (Int.pow 2 31))
  -- conversions
  t "int-toNumber" (show (Int.toNumber 5))
  t "int-fromNumber-ok" (show (Int.fromNumber 5.0))
  t "int-fromNumber-frac" (show (Int.fromNumber 5.5))
  t "int-fromNumber-big" (show (Int.fromNumber 1.0e10))
  t "int-floor" (show (Int.floor 3.7))
  t "int-floor-neg" (show (Int.floor (-3.7)))
  t "int-ceil" (show (Int.ceil 3.2))
  t "int-ceil-neg" (show (Int.ceil (-3.2)))
  t "int-round" (show (Int.round 3.5))
  t "int-round-neg" (show (Int.round (-3.5)))
  t "int-trunc" (show (Int.trunc 3.9))
  t "int-trunc-neg" (show (Int.trunc (-3.9)))
  -- radix
  t "int-hex" (Int.toStringAs Int.hexadecimal 255)
  t "int-hex-neg" (Int.toStringAs Int.hexadecimal (-255))
  t "int-binary" (Int.toStringAs Int.binary 10)
  t "int-octal" (Int.toStringAs Int.octal 64)
  t "int-fromString" (show (Int.fromString "42"))
  t "int-fromString-neg" (show (Int.fromString "-42"))
  t "int-fromString-bad" (show (Int.fromString "4x2"))
  t "int-fromString-empty" (show (Int.fromString ""))
  t "int-fromStringAs-hex" (show (Int.fromStringAs Int.hexadecimal "ff"))
  t "int-fromStringAs-bin" (show (Int.fromStringAs Int.binary "1010"))
  t "int-even" (show (Int.even 4))
  t "int-odd" (show (Int.odd 4))
  -- bits (JS int32 semantics)
  t "bits-and" (show (Bits.and 12 10))
  t "bits-or" (show (Bits.or 12 10))
  t "bits-xor" (show (Bits.xor 12 10))
  t "bits-shl" (show (Bits.shl 1 4))
  t "bits-shl-wrap" (show (Bits.shl 1 31))
  t "bits-shr" (show (Bits.shr (-16) 2))
  t "bits-zshr" (show (Bits.zshr (-1) 0))
  t "bits-zshr-shift" (show (Bits.zshr (-16) 2))
  t "bits-complement" (show (Bits.complement 5))
  -- Number show: the JS toString formatting rules
  t "num-show-simple" (show 1.5)
  t "num-show-int" (show 5.0)
  t "num-show-neg" (show (-3.25))
  t "num-show-zero" (show 0.0)
  t "num-show-negzero" (show (-0.0))
  t "num-show-tenth" (show 0.1)
  t "num-show-e10" (show 1.0e10)
  t "num-show-e20" (show 1.0e20)
  t "num-show-e21" (show 1.0e21)
  t "num-show-e22" (show 1.0e22)
  t "num-show-micro" (show 0.000001)
  t "num-show-e-7" (show 0.0000001)
  t "num-show-e-7-mant" (show 1.5e-7)
  t "num-show-precise" (show 0.30000000000000004)
  t "num-show-third" (show (1.0 / 3.0))
  t "num-show-max" (show 1.7976931348623157e308)
  t "num-show-min" (show 5.0e-324)
  t "num-add-fp" (show (0.1 + 0.2))
  -- Number division edges
  t "num-div" (show (7.0 / 2.0))
  t "num-div-zero" (show (1.0 / 0.0))
  t "num-div-negzero" (show ((-1.0) / 0.0))
  t "num-div-zerozero" (show (0.0 / 0.0))
  -- Math functions
  t "num-sqrt" (show (Num.sqrt 16.0))
  t "num-sqrt-neg" (show (Num.sqrt (-1.0)))
  t "num-abs" (show (Num.abs (-2.5)))
  t "num-floor" (show (Num.floor (-2.5)))
  t "num-ceil" (show (Num.ceil (-2.5)))
  t "num-round" (show (Num.round 2.5))
  t "num-round-neg" (show (Num.round (-2.5)))
  t "num-trunc" (show (Num.trunc (-2.7)))
  t "num-sign" (show (Num.sign (-3.0)))
  t "num-pow" (show (Num.pow 2.0 10.0))
  t "num-pow-frac" (show (Num.pow 4.0 0.5))
  t "num-pow-negbase" (show (Num.pow (-8.0) (1.0 / 3.0)))
  t "num-log" (show (Num.log 1.0))
  t "num-log-neg" (show (Num.log (-1.0)))
  t "num-exp" (show (Num.exp 0.0))
  t "num-sin-zero" (show (Num.sin 0.0))
  t "num-cos-zero" (show (Num.cos 0.0))
  t "num-atan2" (show (Num.atan2 1.0 1.0))
  t "num-asin-oob" (show (Num.asin 2.0))
  t "num-remainder" (show (Num.remainder 7.5 2.0))
  t "num-remainder-neg" (show (Num.remainder (-7.5) 2.0))
  t "num-min" (show (Num.min 1.0 2.0))
  t "num-max" (show (Num.max 1.0 2.0))
  t "num-isNaN" (show (Num.isNaN (0.0 / 0.0)))
  t "num-isFinite" (show (Num.isFinite (1.0 / 0.0)))
  t "num-fromString" (show (Num.fromString "3.5"))
  t "num-fromString-int" (show (Num.fromString "42"))
  t "num-fromString-exp" (show (Num.fromString "1e3"))
  t "num-fromString-bad" (show (Num.fromString "abc"))
  t "num-infinity-show" (show (Num.infinity))
  t "num-nan-show" (show (Num.nan))
